# Generated by Django 3.0.7 on 2020-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default='PUB8Xz5LfetkC8UQ1JbX4m26grrATdND6EM', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default='SECwl4tWSCLKQ6hHGTWFMfkiiYcjdYlNZTm', max_length=50),
        ),
    ]
