# Generated by Django 3.0.7 on 2020-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200622_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(max_length=50),
        ),
    ]
